DiaryAndCodeHub/Controllers/CodeController.cs
using DataAccess.Implementation;
using DiaryAndCodeHub.Helper;
using Models;
using Models.ViewModel;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Security.Claims;
using System.Threading;
using System.Web;
using System.Web.Mvc;
using System.Web.UI.WebControls;

namespace DiaryAndCodeHub.Controllers
{
    [Authorize(Roles ="User")]
    public class CodeController : Controller
    {
        private readonly UnitOfWork unitOfWork = new UnitOfWork();

        // GET: Code
        public ActionResult Index()
        {
            var identity = (ClaimsPrincipal)Thread.CurrentPrincipal;

            IEnumerable<Claim> claims = identity.Claims;


            var currentUsername = claims.Where(c => c.Type == ClaimTypes.Name).Select(c => c.Value).SingleOrDefault();
            var a =unitOfWork.InpcodeRepository.GetAll(filter:m=>m.UserCreated==currentUsername);

            return View(a);
        }
        public ActionResult Create() {
            InpCodes codes = new InpCodes();
            return View(codes);
        
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        [ValidateInput(false)]
        public ActionResult Create(InpCodes code,List<HttpPostedFileBase> Images) {
            if (ModelState.IsValid)
            {
                code.Id = Guid.NewGuid();
                List<InpCodesImages> im = new List<InpCodesImages>();
                if (Images.Count > 0)
                {
                    foreach (var images in Images)
                    {
                        if (images != null)
                        {
                            if (images.ContentLength > 0)
                            {

                                var fileName = Path.GetFileName(images.FileName);
                                var fileName1 = Path.GetFileNameWithoutExtension(images.FileName);

                                // extract only the fielname
                                var ext = Path.GetExtension(fileName.ToLower());            //extract only the extension of filename and then convert it into lower case.
                                if (Extension.ImageExt.Contains(ext.ToUpper()))
                                {


                                    string firstpath1 = "~/Files/";
                                    string secondpath = "~/Files/Code/";
                                    string ThirdPath = "~/Files/Code/Images";
                                    string ForthPath = "~/Files/Code/Images/" + code.Id + "/";
                                    string ForthPath1 = "/Files/Code/Images/" + code.Id + "/";

                                    bool exists1 = System.IO.Directory.Exists(Server.MapPath(firstpath1));
                                    bool exists2 = System.IO.Directory.Exists(Server.MapPath(secondpath));
                                    bool exists3 = System.IO.Directory.Exists(Server.MapPath(ThirdPath));
                                    bool exists4 = System.IO.Directory.Exists(Server.MapPath(ForthPath));

                                    if (!exists1)
                                    {
                                        System.IO.Directory.CreateDirectory(Server.MapPath(firstpath1));

                                    }
                                    if (!exists2)
                                    {
                                        System.IO.Directory.CreateDirectory(Server.MapPath(secondpath));

                                    }

                                    if (!exists3)
                                    {
                                        System.IO.Directory.CreateDirectory(Server.MapPath(ThirdPath));

                                    }

                                    if (!exists4)
                                    {
                                        System.IO.Directory.CreateDirectory(Server.MapPath(ForthPath));

                                    }
                                    var path = Server.MapPath(ForthPath + fileName1 + ext);
                                    InpCodesImages img = new InpCodesImages();
                                    img.ImagePath = ForthPath1 + fileName1 + ext;
                                    img.Id = Guid.NewGuid();
                                    //img.Name = images.FileName;
                                    im.Add(img);
                                    images.SaveAs(path);
                                }
                            }
                        }
                    }
                }
                code.inpCodesImages = im;
                unitOfWork.InpcodeRepository.Insert(code);
                unitOfWork.Save();
                return RedirectToAction("Index");
            }
            return View();

        
        }
        public ActionResult Edit(Guid id)
        {
           
            var a = unitOfWork.InpcodeRepository.GetById(id);
            if(a==null)
            {
                return HttpNotFound();
            }
            return View(a);

        }
        public ActionResult Details(Guid id)
        {
            var a = unitOfWork.InpcodeRepository.GetById(id);
            if (a == null)
            {
                return HttpNotFound();
            }
            var b= unitOfWork.InpImageRepository.GetAll(filter: m => m.InpCodesId == id);
            CodeHubVm v = new CodeHubVm();
            v.Inpcodes = a;
            v.Img = b;

            return View(v);

        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [ValidateInput(false)]
        public ActionResult Edit(InpCodes code,List<HttpPostedFileBase> Images)
        {
            if (ModelState.IsValid)
            {
             
                    List<InpCodesImages> im = new List<InpCodesImages>();
                    int i = 0;

                    if (Images.Count > 0)
                    {
                        foreach (var images in Images)
                        {
                            if (images != null)
                            {
                                if (images.ContentLength > 0)
                                {

                                    var fileName = Path.GetFileName(images.FileName);
                                    var fileName1 = Path.GetFileNameWithoutExtension(images.FileName);

                                    // extract only the fielname
                                    var ext = Path.GetExtension(fileName.ToLower());            //extract only the extension of filename and then convert it into lower case.
                                    if (Extension.ImageExt.Contains(ext.ToUpper()))
                                    {
                                        if (i ==0)
                                        {
                                            List<InpCodesImages> imgs = unitOfWork.InpImageRepository.GetAll(filter: m => m.InpCodesId == code.Id).ToList();
                                            DeleteFolder.ClearFolder(Server.MapPath("~/Files/Code/Images/" + code.Id + "/"));
                                            foreach(var item in imgs)
                                            {
                                                unitOfWork.InpImageRepository.Delete(item.Id);
                                            }
                                            
                                            
                                            
                                            i++;
                                        }
                                        string firstpath1 = "~/Files/";
                                        string secondpath = "~/Files/Code/";
                                        string ThirdPath = "~/Files/Code/Images";
                                        string ForthPath = "~/Files/Code/Images/" + code.Id + "/";
                                        string ForthPath1 = "/Files/Code/Images/" + code.Id + "/";

                                        bool exists1 = System.IO.Directory.Exists(Server.MapPath(firstpath1));
                                        bool exists2 = System.IO.Directory.Exists(Server.MapPath(secondpath));
                                        bool exists3 = System.IO.Directory.Exists(Server.MapPath(ThirdPath));
                                        bool exists4 = System.IO.Directory.Exists(Server.MapPath(ForthPath));

                                        if (!exists1)
                                        {
                                            System.IO.Directory.CreateDirectory(Server.MapPath(firstpath1));

                                        }
                                        if (!exists2)
                                        {
                                            System.IO.Directory.CreateDirectory(Server.MapPath(secondpath));

                                        }

                                        if (!exists3)
                                        {
                                            System.IO.Directory.CreateDirectory(Server.MapPath(ThirdPath));

                                        }

                                        if (!exists4)
                                        {
                                            System.IO.Directory.CreateDirectory(Server.MapPath(ForthPath));

                                        }
                                        var path = Server.MapPath(ForthPath + fileName1 + ext);
                                        InpCodesImages img = new InpCodesImages();
                                        img.Id = Guid.NewGuid();
                                        img.ImagePath = ForthPath1 + fileName1 + ext;
                                        //img.InpCodesId = code.Id;
                                        //img.Name = images.FileName;

DiaryAndCodeHub/Views/Code/Create.cshtml
@model Models.InpCodes
@using Helpers
@using DiaryAndCodeHub.Helper
@{
    ViewBag.Title = "Create";
}


@using (Html.BeginForm("Create", "code", FormMethod.Post, new { @enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    <div class="form-row">
        <div class="col-md-10">

            <div class="form-group">
                @Html.LabelFor(model => model.Topic, htmlAttributes: new { @class = "control-label" })
                @Html.EditorFor(model => model.Topic, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Topic, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="col-md-10">

            <div class="form-group">
                @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label" })
                @Html.CkeditorFor(model => model.Description)
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="col-md-3">

            <div class="form-group">
                <label> Images</label>

                @Html.File("Images", new { id= "fileupload",@class="form-control-file", name = "Images",multiple="multiple" })
              @*<input type="file" id="fileupload" class="form-control-file" name="Images" multiple />*@
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>
        <div id="dvPreview">
        </div>
        <div class="col-md-12">

            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
                @Html.ActionLink("Back to List", "Index")
                @Html.Image("/abc")
            </div>
        </div>
    </div>
}


<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
<script language="javascript" type="text/javascript">
    $(function () {
        $("#fileupload").change(function () {
            if (typeof (FileReader) != "undefined") {
                var dvPreview = $("#dvPreview");
                dvPreview.html("");
                var regex = /^([a-zA-Z0-9\s_\\.\-:])+(.jpg|.jpeg|.gif|.png|.bmp)$/;
                $($(this)[0].files).each(function () {
                    var file = $(this);
                    if (regex.test(file[0].name.toLowerCase())) {
                        var reader = new FileReader();
                        reader.onload = function (e) {
                            var img = $("<img />");
                            img.attr("style", "height:100px;width: 100px");
                            img.attr("src", e.target.result);
                            dvPreview.append(img);
                        }
                        reader.readAsDataURL(file[0]);
                    } else {
                        alert(file[0].name + " is not a valid image file.");
                        dvPreview.html("");
                        return false;
                    }
                });
            } else {
                alert("This browser does not support HTML5 FileReader.");
            }
        });
    });
</script>

DiaryAndCodeHub/Views/Code/Details.cshtml
@model Models.ViewModel.CodeHubVm
<style>
    pre {
        background-color: #EFF0F1;
        border: 1px solid #DDD;
        padding: 10px;
    }
</style>
<div class="row">
    <div class="col-md-12">
        <input type="button" value="Copy code to clipboard" class="btn btn-primary" style="float:right;padding-bottom:10px;margin-bottom:10px;" onclick="selectElementContents();">
    </div>
</div>
@Html.Raw(Model.Inpcodes.Description)

<div class="card">
    <div class="card-header">
        <h4 class="card-title">Images</h4>
    </div>
    <div class="card-body bg-body-bg">
        <div class="row" id="drag-cards">
            @foreach (var item in Model.Img)
            {
                <div class="col-lg-3">
                    <div class="card mb-3">
                        <a href="@Url.Content("~"+item.ImagePath)" data-fancybox="gallery">
                            <img src="@Url.Content("~"+item.ImagePath)" alt="@Model.Inpcodes.Topic" class="card-img-top">
                        </a>
                        @*<div class="card-body">
                                <h5 class="card-title mb-0">Person 1</h5>
                            </div>*@
                    </div>
                </div>
            }
        </div>
    </div>
</div>
@section Scripts{

    <script>
        function selectElementContents() {
            var textToCopy = document.querySelector('.prettyprint');
            var currentRange;
            if (document.getSelection().rangeCount > 0) {
                //the user has a text selection range, store it
                currentRange = document.getSelection().getRangeAt(0);
                //remove the current selection
                window.getSelection().removeRange(currentRange);
            }
            else {
                //they didn't have anything selected
                currentRange = false;
            }

            //create a selection range
            var CopyRange = document.createRange();
            //choose the element we want to select the text of
            CopyRange.selectNode(textToCopy);
            //select the text inside the range
            window.getSelection().addRange(CopyRange);
            //copy the text to the clipboard
            document.execCommand("copy");

            //remove our selection range
            window.getSelection().removeRange(CopyRange);

            //return the old selection range
            if (currentRange) {
                window.getSelection().addRange(currentRange);
            }

            alert("successfully copied to clipboard");
        }
    </script>

}




     

DiaryAndCodeHub/Views/Code/Edit.cshtml
@model Models.InpCodes
@using DiaryAndCodeHub.Helper
@{
    ViewBag.Title = "Create";
}


@using (Html.BeginForm("eDIT", "code", FormMethod.Post, new { @enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(M => M.Id)
    @Html.HiddenFor(m => m.DateCreated)
    @Html.HiddenFor(m => m.UserCreated)
    <div class="form-row">
        <div class="col-md-10">

            <div class="form-group">
                @Html.LabelFor(model => model.Topic, htmlAttributes: new { @class = "control-label" })
                @Html.EditorFor(model => model.Topic, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Topic, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="col-md-10">

            <div class="form-group">
                @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label" })
                @Html.CkeditorFor(model => model.Description)
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="col-md-3">

            <div class="form-group">
                <label> Images</label>
                <input type="file" class="form-control-file" id="fileupload" name="Images" multiple />
                @Html.ValidationMessageFor(model => model.Images, "", new { @class = "text-danger" })
            </div>
        </div>
        <div id="dvPreview">

        </div>
        <div class="col-md-12">

            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
                @Html.ActionLink("Back to Home", "Index")

            </div>
        </div>
    </div>
}


<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
<script language="javascript" type="text/javascript">
    $(function () {
        $("#fileupload").change(function () {
            if (typeof (FileReader) != "undefined") {
                var dvPreview = $("#dvPreview");
                dvPreview.html("");
                var regex = /^([a-zA-Z0-9\s_\\.\-:])+(.jpg|.jpeg|.gif|.png|.bmp)$/;
                $($(this)[0].files).each(function () {
                    var file = $(this);
                    if (regex.test(file[0].name.toLowerCase())) {
                        var reader = new FileReader();
                        reader.onload = function (e) {
                            var img = $("<img />");
                            img.attr("style", "height:100px;width: 100px");
                            img.attr("src", e.target.result);
                            dvPreview.append(img);
                        }
                        reader.readAsDataURL(file[0]);
                    } else {
                        alert(file[0].name + " is not a valid image file.");
                        dvPreview.html("");
                        return false;
                    }
                });
            } else {
                alert("This browser does not support HTML5 FileReader.");
            }
        });
    });
</script>

DiaryAndCodeHub/Views/Code/Index.cshtml
@model IEnumerable<Models.InpCodes>

@{
    ViewBag.Title = "Index";
}


<p>
    @Html.ActionLink("Add Codes", "Create", null, new { @class = "btn btn-primary" })
</p>
<table class="table" id="tbl">
    <thead>
        <tr>
            <th>
            </th>
            <th>

            </th>
        </tr>
    </thead>
    <tbody>

        @foreach (var item in Model)
        {
            <tr>

                <td>
                    <div style="background-color:#EFF0F1;
                        border: 1px solid #DDD;
                            padding: 10px;">
                        <a style="color:black;text-decoration:none" href="@Url.Action("Details", "Code", new { id=item.Id })">  @Html.DisplayFor(modelItem => item.Topic)</a><br />
                    </div>
                </td>
                <td>
                    <div style="background-color:#EFF0F1;
                        border: 1px solid #DDD;
                            padding: 10px;">
                        <a style="color:black;text-decoration:none" href="@Url.Action("Edit","Code",new { id=item.Id })">Edit</a>
                        </div>
                </td>

                @*<td>
                        @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
                        @Html.ActionLink("Details", "Details", new { id=item.Id }) |
                        @Html.ActionLink("Delete", "Delete", new { id=item.Id })
                    </td>*@
            </tr>
        }
    </tbody>
</table>
<link type="text/css" href="~/Content/vendor-bootstrap-datatables.css" rel="stylesheet">

@section Scripts{
    <script src="~/Scripts/jquery-3.4.1.js"></script>
    <script src="~/vendors/jquery.dataTables.js"></script>
    <script src="~/vendors/dataTables.bootstrap4.js"></script>
    <script src="/Vendors/dataTables.bootstrap4.js"></script>
    <script>



        $(document).ready(function () {
           
            $("#tbl").dataTable({
                "pageLength": 50,
                "lengthChange": false
            });
            $('.dataTables_filter input[type="search"]').css(
                { 'width': '350px', 'display': 'inline-block' }
            );
        })
    </script>
}