DiaryAndCodeHub/Controllers/InpWorkController.cs
using DataAccess.Implementation;
using Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading;
using System.Web;
using System.Web.Mvc;

namespace DiaryAndCodeHub.Controllers
{
    [Authorize(Roles = "User")]

    public class InpWorkController : Controller
    {
      
            private readonly UnitOfWork unitOfWork = new UnitOfWork();

            // GET: Code
            public ActionResult Index()
            {
            var identity = (ClaimsPrincipal)Thread.CurrentPrincipal;

            IEnumerable<Claim> claims =   identity.Claims;


            var currentUsername = claims.Where(c => c.Type == ClaimTypes.Name).Select(c => c.Value).SingleOrDefault();

            var a = unitOfWork.InpWorksRepository.GetAll(filter:m=>m.UserCreated==currentUsername);
                return View(a);
            }
            public ActionResult Create()
            {
            InpWorks inp = new InpWorks();
                return View(inp);

            }
            [HttpPost]
            [ValidateAntiForgeryToken]
            [ValidateInput(false)]
            public ActionResult Create(InpWorks code)
            {
                if (ModelState.IsValid)
                {
                    code.Id = Guid.NewGuid();

                    unitOfWork.InpWorksRepository.Insert(code);
                    unitOfWork.Save();
                    return RedirectToAction("Index");
                }
                return View();


            }
            public ActionResult Edit(Guid id)
            {
                var a = unitOfWork.InpWorksRepository.GetById(id);
                if (a == null)
                {
                    return HttpNotFound();
                }
                return View(a);

            }
            public ActionResult Details(Guid id)
            {
                var a = unitOfWork.InpWorksRepository.GetById(id);
                if (a == null)
                {
                    return HttpNotFound();
                }
               

                return View(a);

            }

            [HttpPost]
            [ValidateAntiForgeryToken]
            [ValidateInput(false)]
            public ActionResult Edit(InpWorks code)
            {
                if (ModelState.IsValid)
                {



                unitOfWork.InpWorksRepository.Update(code);
                    unitOfWork.Save();
                    return RedirectToAction("Index");
                }


                return View(code);


            }

        }

    }

DiaryAndCodeHub/Views/InpWork/Create.cshtml
@model Models.InpWorks
@using DiaryAndCodeHub.Helper
@{
    ViewBag.Title = "Create";
}

@using (Html.BeginForm("Create", "InpWork", FormMethod.Post, new { @enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    <div class="form-row">
        <div class="col-md-10">

            <div class="form-group">
                @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label" })
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="col-md-10">

            <div class="form-group">
                @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label" })
                @Html.CkeditorFor(model => model.Description)
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="col-md-3">

            <div class="form-group">
                <label> Date</label>
                <input type="date" name="date" multiple />
                @Html.ValidationMessageFor(model => model.Date, "", new { @class = "text-danger" })
            </div>
        </div>
        
        <div class="col-md-12">

            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
                @Html.ActionLink("Back to List", "Index")

            </div>
        </div>
    </div>
}

DiaryAndCodeHub/Views/InpWork/Details.cshtml
@model Models.InpWorks
<style>
    pre {
        background-color: #EFF0F1;
        border: 1px solid #DDD;
        padding: 10px;
    }
</style>

<div class="card">
    <div class="card-header">
        <h4 class="card-title">@Model.Date</h4>
    </div>
    <div class="card-body bg-body-bg">
        <div class="row" id="drag-cards">
            @Html.Raw(Model.Description)

        </div>
    </div>
</div>

DiaryAndCodeHub/Views/InpWork/Edit.cshtml
@model Models.InpWorks
@using DiaryAndCodeHub.Helper
@{
    ViewBag.Title = "Create";
}

@using (Html.BeginForm("Edit", "InpWork", FormMethod.Post, new { @enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(m => m.Id)
    @Html.HiddenFor(m => m.DateCreated)
    @Html.HiddenFor(m => m.UserCreated)

    <div class="form-row">
        <div class="col-md-10">

            <div class="form-group">
                @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label" })
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="col-md-10">

            <div class="form-group">
                @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label" })
                @Html.CkeditorFor(model => model.Description)
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="col-md-3">

            <div class="form-group">
                <label> Date</label>
                <input type="date" name="date" multiple />
                @Html.ValidationMessageFor(model => model.Date, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="col-md-12">

            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
                @Html.ActionLink("Back to List", "Index")

            </div>
        </div>
    </div>
}

DiaryAndCodeHub/Views/InpWork/Index.cshtml
@model IEnumerable<Models.InpWorks>


<p>
    @Html.ActionLink("Add Works", "Create", null, new { @class = "btn btn-primary" })
</p>
<table class="table" id="tbl">
    <thead>
        <tr>
            <th>
            </th>
            <th>

            </th>
        </tr>
    </thead>
    <tbody>

        @foreach (var item in Model)
        {
        <tr  style="background-color:#EFF0F1;
        border: 1px solid #DDD;
        padding: 10px;">

            <td>
                <div>
                    <a style="color:black;text-decoration:none" href="@Url.Action("Details", "InpWork", new { id=item.Id })">  @Html.DisplayFor(modelItem => item.Title)</a><br />
                    <a style="color:black;text-decoration:none" href="@Url.Action("Edit","InpWork",new { id=item.Id })">Edit</a>
                </div>
            </td>

            <td>
                <div>
                    @item.Date
                    </div>
                </td>
                    @*<td>
                    @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
                    @Html.ActionLink("Details", "Details", new { id=item.Id }) |
                    @Html.ActionLink("Delete", "Delete", new { id=item.Id })
                </td>*@
        </tr>
        }
    </tbody>
</table>
<link type="text/css" href="~/Content/vendor-bootstrap-datatables.css" rel="stylesheet">

@section Scripts{
    <script src="~/Scripts/jquery-3.4.1.js"></script>
    <script src="~/vendors/jquery.dataTables.js"></script>
    <script src="~/vendors/dataTables.bootstrap4.js"></script>
    <script src="/Vendors/dataTables.bootstrap4.js"></script>
    <script>



        $(document).ready(function () {

            $("#tbl").dataTable({
                "pageLength": 50,
                "lengthChange": false
            });
            $('.dataTables_filter input[type="search"]').css(
                { 'width': '350px', 'display': 'inline-block' }
            );
        })
    </script>
}